### ISSUE TITLE
Don't show subtitle when text is null/empty

### ISSUE THREAD

**Issue by timusus** [HendraAnggrian/collapsingtoolbarlayout-subtitle#1]
Currently, if the subtitle text is empty/null, it shows up as "testing".

It would be great if the subtitle was hidden, and this just acted like a regular `CollapsingToolbarLayout` when the subtitle text is empty/null.

**Comment by HendraAnggrian** [comment]
@timusus my bad, I have uploaded version 0.3.1 that should behave exactly like what you have described, let me know if it's not.

And I just wanna say I love your `recyclerview-fastscroll`!

**Comment by timusus** [comment]
Wow, that was quick! Good work, I'll be sure to check it out tomorrow.

Open source is great, isn't it?!
