### ISSUE TITLE
Toolbar menu icons issue

### ISSUE THREAD

**Issue by karmil32** [HendraAnggrian/collapsingtoolbarlayout-subtitle#10]
Hello. 
First of all - thanks for great library!
Today, after upgrade this lib to new version I noticed a issue with toolbar icons. 
These icons are not vertically centered in toolbar.
Heres example how it looks in my app:
https://www.dropbox.com/s/obqtbmfxh1bd3rr/toolbar_issue.PNG?dl=0
https://www.dropbox.com/s/8ujbzprix420t1q/toolbar_issue2.PNG?dl=0

When I use native CollapsingToolbarLayout everything is ok.

You can simply reproduce this bug in Your sample app. Just add this line to "onCreateOptionsMenu" method:
`toolbar.menu.add(R.id.item_article_bookmark)`

And now you can see:
https://www.dropbox.com/s/d0nqc5vu8p741i6/toolbar_issue3.PNG?dl=0

**Comment by HendraAnggrian** [comment]
Hi @karmil32. Thanks for the detailed report! I'll see what I can do in next couple days.

Anyway, I'm sorry if this issue isn't there on previous version. Porting this lib to Kotlin is essentially rewroting most of its components, opening up possibility to larger bugs and inconsistencies.

**Comment by hannesa2** [comment]
@karmil32 which was your previous version, where it works properly ?
@HendraAnggrian almost not noteworthy, but I like to see when on this issue a progres will be done

**Comment by karmil32** [comment]
Currently using ''com.hendraanggrian:collapsingtoolbarlayout-subtitle:0.5.2@aar' and all is ok

**Comment by hannesa2** [comment]
@karmil32 for your info, right now I checked out commit 14c5b08ea1f (before kotlin in lib, means one commit after v 0.7.0) and all is fine

**Comment by hannesa2** [comment]
@karmil32 when I uses 0.7.0 I can't use supportLib 26.1.0 https://github.com/HendraAnggrian/collapsingtoolbarlayout-subtitle/issues/13

**Comment by HendraAnggrian** [comment]
@karmil32 @hannesa2 sorry it took months for me to fix this issue, I was preoccupied with other projects.

Version 26.1.0 is out and it should fix this issue. This lib now has the same versioning as support lib since there is no future development planned with this lib, only patches that will allow it to work on future support lib version.
