### ISSUE TITLE
Library no longer available in Java

### ISSUE THREAD

**Issue by timusus** [hendraanggrian/collapsingtoolbarlayout-subtitle#11]
I would recommend that the Kotlin version of this library be hosted under a separate branch - although I love Kotlin, it's a pretty heavy duty dependency if a Java only Android app wants to use the library.

Obviously this comes with extra maintenance overhead..

**Comment by hendraanggrian** [comment]
Hi Tim! My bad I somehow missed this issue. During the time I didn't notice this issue, I fell more and more in love with Kotlin, and I'm under the impression that it is completely compatible with Java-only projects. Moreover, Realm is doing an amazing [report](https://realm.io/realm-report/) that concludes Kotlin are already amount to 20% of all Android apps.

But I do understand almost 1MB that Kotlin std lib carries are heavy for some. I'll keep this open for a while, I will create a separate module written only in Java if more people request it.

**Comment by giaur500** [comment]
@timusus I used recent version in my Java project without any problems. Kotlin and Java (as far as I know) can be mixed without any restrictions, also if you used lib dependency, it you don't even need to know if lib is Kotlin or Java, it does not matter at all.

**Comment by timusus** [comment]
The problem is that a Kotlin based library requires you to integrate Kotlin into your build, which increases your method count and apk size. It's a lot of overhead if the project is otherwise Kotlin-free.

I love Kotlin and I've used it for many projects, but I'd rather a library remain in Java so I can use it in Kotlin or Java projects, rather than have it converted to Kotlin forcing consumers to integrate Kotlin.

This is a low maintenance library, so I don't really see what's to gain by converting it to Kotlin. It also makes porting future changes from the support library more difficult.

**Comment by giaur500** [comment]
> The problem is that a Kotlin based library requires you to integrate Kotlin into your build, which increases your method count and apk size. It's a lot of overhead if the project is otherwise Kotlin-free.

Well, it's true. Kotlin libs must be embedded in resulting apk. But it seems it affects apk size only, not app performance.

**Comment by timusus** [comment]
I'm not suggesting there is a performance impact. I'm just questioning why this Java library was converted to Kotlin, preventing consumers from deciding whether their project should incorporate Kotlin, when there's not much to be gained from the Kotlin conversion, and it makes maintenance more difficult in some ways.

**Comment by giaur500** [comment]
> I'm just questioning why this Java library was converted to Kotlin,  preventing consumers from deciding whether their project should incorporate Kotlin,

Well, I guess dev likes Kotlin, it's nothing wrong. You can always convert it back to Java if you wish (you have full sources). Or develop your own library. Complains are out of place when somebody decides to share his work for free for everyone.

**Comment by timusus** [comment]
I think you misunderstand.This is not a complaint, but rather a discussion.

I appreciate the work done by the owner of this repository. I contributed to it myself in its early stages. 

I think it's bad library design to force adoption of an alternative language for no real gain - as I said, this library needs to be ported from the support libraries to be kept up to date. If anything, Kotlin conversion will make future changes more difficult. 

I think it's worth raising the question - why force consumers to integrate Kotlin purely because you prefer Kotlin? This is a breaking API change, and I'm just not really sure that it makes a lot of sense. If the developer agrees, we could revert the library to Java, removing the Kotlin dependency, which is going to be useful to myself and many other consumers.

As an open source developer myself, I like to make my libraries available to as wider audience as possible, and think very carefully about the library's dependencies.

**Comment by hendraanggrian** [comment]
I completely agree: there isn't a good answer to why this lib should use Kotlin. I was selfishly using it as a testbed since I'm still pretty new to Kotlin.

But to be fair, it wasn't all a bad call. It did reduce the codebase about 20-30%, it isn't worth extra dependency (not to mention some lint checks are also broken), but it is worth mentioning that less code makes easy reading.

I plan to revert it back to Java on upcoming version 27.0.2. Version 26.1.0 and 27.0.1, however, will still be stuck with Kotlin.

**Comment by hendraanggrian** [comment]
Hi @timusus , version `1.0.0-beta01` with AndroidX has just been released without Kotlin in it.
