### ISSUE TITLE
supportActionBar and setDisplayHomeAsUpEnabled(true)

### ISSUE THREAD

**Issue by hannesa2** [HendraAnggrian/collapsingtoolbarlayout-subtitle#12]
When I use collapsingtoolbarlayout-subtitle 0.8.0 and update to Android O and with 

`supportActionBar?.setDisplayHomeAsUpEnabled(true)`

it doesn't looks nice

![image](https://user-images.githubusercontent.com/3314607/30817992-a503aeda-a21a-11e7-8747-6df5bbe6fdbf.png)
or 
![image](https://user-images.githubusercontent.com/3314607/30818374-a950b464-a21b-11e7-9991-c60e822af0a9.png)
you can follow https://github.com/hannesa2/collapsingtoolbarlayout-subtitle/tree/Android3_setDisplayHomeAsUpEnabled_true

**Comment by HendraAnggrian** [comment]
Should be fixed with version 26.1.0 as stated on attached issue. Although I haven't tested that navigation icon. Please try version 26.1.0 and let me know it still hasn't been fixed.

**Comment by hannesa2** [comment]
works like a charm. Thank you !
