### ISSUE TITLE
Android 0

### ISSUE THREAD

**Issue by hannesa2** [HendraAnggrian/collapsingtoolbarlayout-subtitle#13]
because of https://github.com/HendraAnggrian/collapsingtoolbarlayout-subtitle/issues/12 I revert to using lib 0.7.0 but here it can't be used with supportLib 26.1.0

>  java.lang.NoSuchMethodError: No static method objectEquals(Ljava/lang/Object;Ljava/lang/Object;)Z in class Landroid/support/design/widget/ViewUtils; or its super classes (declaration of 'android.support.design.widget.ViewUtils' appears in /data/app/de.xxx-CwA8318Qch206prKNiDGEQ==/base.apk:classes2.dex)
>                                                                                    at android.support.design.widget.SubtitleCollapsingToolbarLayout.onWindowInsetChanged(SubtitleCollapsingToolbarLayout.java:202)
>                                                                                    at android.support.design.widget.SubtitleCollapsingToolbarLayout$1.onApplyWindowInsets(SubtitleCollapsingToolbarLayout.java:169)
>                                                                                    at android.support.v4.view.ViewCompat$ViewCompatApi21Impl$1.onApplyWindowInsets(ViewCompat.java:1256)

**Comment by HendraAnggrian** [comment]
Should be fixed with version 26.1.0, as stated in attached issue. Don't hesitate to reopen this issue if you encounter any problem with this version.
