### ISSUE TITLE
collapse Toolbar programmatically

### ISSUE THREAD

**Issue by MeinLieberScholli** [HendraAnggrian/collapsingtoolbarlayout-subtitle#15]
Hi,

it would be great if you could provide a function to collapse the toolbar programmatically.
Or is a workaround with the existing functions possible?

Cheers.

**Comment by HendraAnggrian** [comment]
I haven't tried it, but I imagine there is a function to hide or show AppBarLayout, which should be a direct parent of CollapsingToolbarLayout. Would you mind trying it? I'm sorry I couldn't help much I'm driving.

**Comment by MeinLieberScholli** [comment]
You are right. Thanks for the help^^
