### ISSUE TITLE
cannot find symbol method makeRestartActivityTask(ComponentName)

### ISSUE THREAD

**Issue by basmasrour** [hendraanggrian/collapsingtoolbarlayout-subtitle#18]
Hi all:
after compile collapsingtoolbarlayout-subtitle, can't build project for this error:
Error:(155, 53) error: cannot find symbol method makeRestartActivityTask(ComponentName)
IntentCompat.makeRestartActivityTask(cn) : cn is :ComponentName cn = intent.getComponent();

Is there any conflict reason?

**Comment by hendraanggrian** [comment]
Difficult to know without complete stack trace. Try the latest version 27.1.0 and if you still have that error, post the full stack trace here.

**Comment by AmjadAlwareh25** [comment]
Just replace "IntentCompat" with "Intent"
 Intent.makeRestartActivityTask(cn);
