### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.widget.ViewGroupUtils" on path: DexPathList

### ISSUE THREAD

**Issue by AkshayChordiya** [hendraanggrian/collapsingtoolbarlayout-subtitle#20]
Upgrading to Design Support Library v27.1.0 started to cause this issue.

**Comment by hendraanggrian** [comment]
Try importing this library with design library excluded. If it's still not working I will patch the current version 27.1.0.

**Comment by AkshayChordiya** [comment]
I tried this but it didn't work out:
```
implementation ("com.hendraanggrian:collapsingtoolbarlayout-subtitle:27.0.1", {
        exclude group: 'com.android.support', module: 'design'
})
```

**Comment by IanWambai** [comment]
@hendraanggrian Having this same issue. How about removing the whole support library version thing? Seems like you'll have to make a patch every time there's an update to the support library.

**Comment by hendraanggrian** [comment]
@IanWambai yes that is the main drawback of using a library that is based on internal component of support library. And to be honest, I'm currently in the middle of something and don't know when can I patch this library to the latest support library. I'm so sorry.

**Comment by IanWambai** [comment]
That's alright. I'll try find some other way for now. Will check back later.

**Comment by hendraanggrian** [comment]
Hi guys, I have just patched version 27.1.0 to this library. I'm sorry it took so long, I had to also patch [errorbar](https://github.com/hendraanggrian/errorbar) since it is used in testing of this library.

Please try it and let me know how it goes.

**Comment by IanWambai** [comment]
Works perfectly. Thanks!

**Comment by AkshayChordiya** [comment]
It works. Thanks @hendraanggrian for patching.

**Comment by hendraanggrian** [comment]
Glad to know! See you on the next support version.
