### ISSUE TITLE
Support for androidx 1.0.0

### ISSUE THREAD

**Issue by devjn** [hendraanggrian/collapsingtoolbarlayout-subtitle#22]
There are a lot of changes in upcoming revision of support library. The major change is that now coordinatorlayout is a separate module and a lot of internals are now changed.

**Comment by hendraanggrian** [comment]
I will most likely patch it to 28.0.0 when stable version is released, now it's only alpha.

By separate module, do you mean that `CoordinatorLayout` no longer belong in support design library? The internals are always changing every version, it's nothing to worry about.

**Comment by devjn** [comment]
Yes, from developer.android.com:
We have split parts of support-core-ui, support-core-utils, and support-compat into smaller libraries. This change will help us detangle support library dependencies in the future. We now have the following new libraries: 
coordinatorlayout (from design)

**Comment by hendraanggrian** [comment]
Thanks for the news.

In that case, I need to read every line of `CollapsingToolbarLayout` source and resources to find out if this library should also import that new `CoordinatorLayout` library in the future. I will do it when it enters beta/stable. In the meantime, let's keep this issue open.

**Comment by devjn** [comment]
As it was announced yesterday, big [refactor of support library](https://developer.android.com/topic/libraries/support-library/refactor) is coming, so I renamed the issue.

**Comment by hendraanggrian** [comment]
I'm sorry you might have to fill me up on this, I haven't been listening to Android news. What is `androidx 1.0.0`? Is it in any way related to [android-ktx](https://github.com/android/android-ktx)?

**Comment by hendraanggrian** [comment]
Nice to know! Here's what I wonder: should we also change versioning of this library back to 1.0.0?

**Comment by hendraanggrian** [comment]
I think so too. May I ask for a favor to update this thread once the new support library is stable? I could get a head start on this one, new update looks like a big one.

**Comment by devjn** [comment]
version 1.0.0-beta01of AndroidX was recently released and is stated to be feature-complete and its public API surface is stable. Also it is safe to use in production.

**Comment by hendraanggrian** [comment]
What is your source of that information? I don't see new beta build [here](https://developer.android.com/topic/libraries/support-library/revisions).

**Comment by devjn** [comment]
https://developer.android.com/topic/libraries/support-library/androidx-rn#1.0.0b01

**Comment by hendraanggrian** [comment]
`1.0.0-beta01` is released as the first AndroidX patch. It is hosted under new repository and artifact: `com.hendraanggrian.material:subtitlecollapsingtoolbarlayout:1.0.0-beta01`. Thanks for the heads up and see you on next version updates.
