### ISSUE TITLE
Issues with Navigation Drawer

### ISSUE THREAD

**Issue by schott12521** [hendraanggrian/collapsingtoolbarlayout-subtitle#23]
Using this library, my toolbar will hide the navigation drawer hamburger icon when the toolbar is collapsed. Unsure of what could be causing this.

**Comment by hendraanggrian** [comment]
I have some guesses, but it's difficult to pick one without knowing more:
 1. Are you using action toggle from support v7 library?
 2. Are you absolutely sure that such behavior does not appear if you replace `SubtitleCollapsingToolbarLayout` with regular `CollapsingToolbarLayout`?
 3. Your phone/emulator OS version and support library version you're using.

**Comment by schott12521** [comment]
Sure thing, thanks for the quick response!

1. I am using action toggle, specifically: ActionBarDrawerToggle
2. Correct, when using a regular CollapsingToolbarLayout the hamburger icon persisted in the upper left of the action bar regardless or collapsed or expanded state.
3. I am on an OG Pixel XL with Oreo 8.1 and using 27.1.0 support library version

**Comment by hendraanggrian** [comment]
1. The thing is, there's 2 versions of `ActionBarDrawerToggle`, one from `android.support.v4.app` and another from `android.support.v7.app`. Which one are you using?
2. If you replace it with regular back arrow icon (`?homeAsUp` attribute). Does the back arrow still behaves the same way? Just wanna make sure if the issue is related to action bar toggle at all.

**Comment by schott12521** [comment]
1. I'm using `android.support.v7.app.ActionBarDrawerToggle`
2. Yes, the same issue happens with just homeAsUp Enabled as well

**Comment by schott12521** [comment]
Alright sounds great, let me know if I can be of any assistance. The only thing that might help so far is that I was looking at the Debug Overdraw screen and with the normal Collapsing Layout, the title warps from being a box of the full width of the device, to just the width of the text. That does not happen with the Subtitle Collapsing Layout, so maybe we need to change the width? Thank you!

**Comment by hendraanggrian** [comment]
Hi, I've tested example app with back icon (`homeAsUpIndicator`) enabled:

![screenshot_1523203661](https://user-images.githubusercontent.com/11507430/38469629-19ea3060-3b82-11e8-820f-455c3c66cdcb.png)
![screenshot_1523203667](https://user-images.githubusercontent.com/11507430/38469630-1a1d3b7c-3b82-11e8-9900-86a750c3e31e.png)

Safe to say I am unable to recreate the issue you are experiencing. Could you please screenshoot your screen?

**Comment by schott12521** [comment]
Sure! Here is my expanded view: [Expanded](https://imgur.com/a/2UqHK)

and here is my collapsed: [Collapsed](https://imgur.com/a/cnNFf)

I'm not doing anything special with my subtitle collapsing layout, its more or less a standard / out of the box setup. Pixel OG, Android 8.1.0 latest security patch. I will try to get a video of collapsing and what it looks like so maybe we can use that to bug fix? Let me know what else I can do to help.

**Comment by schott12521** [comment]
Damn. Its the little things that can really mess up your development, lol. My issue was that I was setting: 

`android:paddingBottom="50dp"`

which was hiding the icon. Thanks for all of the assistance / great library!

**Comment by hendraanggrian** [comment]
Cool! Let me know when you experience other issues.
