### ISSUE TITLE
Propose app logo

### ISSUE THREAD

**Issue by anaufalm** [hendraanggrian/collapsingtoolbarlayout-subtitle#24]
Hello, Im flat raphic designer. I want to propose a logo for branding your project. Can I make a logo for you?

**Comment by hendraanggrian** [comment]
Hi, yes you very well may. But since this is an open-source project and I do not intend to commercialize it in any way, I'm afraid I can't pay for your work.

I can credit you in readme file and project website (which currently is only javadoc), but that's about all.

**Comment by anaufalm** [comment]
This is open source right? We can contribute anything. :D
I will make it for free for you. If you like you can put my name as a contributor in readme or other.

**Comment by hendraanggrian** [comment]
Yes, and any work you do here may be modified or reused by others in the community. If you can accept that I will gladly accept your contribution. :)

I suggest you create a pull request, as doing so will make your name appear on contributor list.

**Comment by hendraanggrian** [comment]
Sorry for late reply. As much as I would like to use your work, I probably I shouldn't. The icon doesn't resemble the word collapsing, layout, or subtitle. But I do appreciate material design touch there, and just wondering if you could revise it with a model that is more related to current project.

**Comment by anaufalm** [comment]
Logotype is just a option, the primary logo is the logomark. Ok, I'will make another design for you.

**Comment by hendraanggrian** [comment]
Closed for inactivity.
