### ISSUE TITLE
expandedSubtitleTextAppearance bug with shadows

### ISSUE THREAD

**Issue by MikaelMorales** [hendraanggrian/collapsingtoolbarlayout-subtitle#25]
Hi,

Adding shadows around the subtitle when it is expanded using:
`app:expandedSubtitleTextAppearance="@style/CollapsingToolbarShadow"`

with the simple following style doesn't work:
```
<style name="CollapsingToolbarShadow">
      <item name="android:shadowDy">0</item>
      <item name="android:shadowDx">0</item>
      <item name="android:shadowRadius">8</item>
      <item name="android:shadowColor">@color/black</item>
</style>
```
The shadows are not visible on the subtitle, but the same style works with the title.

**Comment by hendraanggrian** [comment]
Hi @MikaelMorales, since I have no experience whatsoever with shadowing, may I see screenshots of expected and actual result of that code snippet?

**Comment by MikaelMorales** [comment]
Yes sure, you can see the difference between the tile with shadows and the subtitle where there are not shown below.
As you can see, shadows are a good way to improve readability in case the background picture is not known apriori.
![collapsingtoolbar](https://user-images.githubusercontent.com/13578763/41355679-62e52206-6f22-11e8-93c0-141454502db2.jpg)

**Comment by hendraanggrian** [comment]
I can see your point. I'll check why such behavior is only appearing on title. If it is quickly fixable, it'll fit with 27.1.1 patch.

Thanks for your contribution!

**Comment by hendraanggrian** [comment]
Hi @MikaelMorales , version `1.0.0-beta01` should fix this issue (but you need to use AndroidX). Feel free to reopen this issue if you find out that it isn't fixed.

**Comment by ArcherEmiya05** [comment]
> 
> 
> Hi @MikaelMorales , version `1.0.0-beta01` should fix this issue (but you need to use AndroidX). Feel free to reopen this issue if you find out that it isn't fixed.

Have you try this style on Android M SDK (23). It's not working though, but works fine on Android 10.
