### ISSUE TITLE
Set subtitle programmatically

### ISSUE THREAD

**Issue by xzeno** [hendraanggrian/collapsingtoolbarlayout-subtitle#27]
How can I change subtitle programmatically?
I tried 
`getSupportActionBar().setSubtitle("text");`
but it did not work

**Comment by hendraanggrian** [comment]
Hi @xzeno, sorry for late reply. When you invoke `getSupportActionBar().setSubtitle("text");`, you are changing the subtitle of `Toolbar`, which is overridden by subtitle of `SubtitleCollapsingToolbarLayout`.

Therefore, you need to invoke `subtitleCollapsingToolbarLayout.setSubtitle("text");` instead.
