### ISSUE TITLE
Title and subtitle display issue.

### ISSUE THREAD

**Issue by jarvisv4** [hendraanggrian/collapsingtoolbarlayout-subtitle#32]
Hello , I just integrated your library and it works perfect, except of one issue. The title and subtitle are not getting left padding as required, they just stick to start of screen which looks just ugly. Can you tell me what am I missing here?

**Comment by hendraanggrian** [comment]
May I see a screenshot please? Also, Android version and phone/emulator model.

**Comment by jarvisv4** [comment]
Hello @hendraanggrian ,thanks for your reply.I just found a fix to it by adding "expandedTitleMarginStart" , but by using this animation starts from that point which results in title and subtitle gets placed far from back button at end of collapsing. I need it to animate only after reaching a percentage height while collapsing. How can I do that?

**Comment by hendraanggrian** [comment]
A

**Comment by hendraanggrian** [comment]
It is technically possible to alter animation, but I feel like it should animate the way CollapsingToolbarLayout works.
