### ISSUE TITLE
New release planned for version 1.1.0 of material ?

### ISSUE THREAD

**Issue by willezs** [hendraanggrian/collapsingtoolbarlayout-subtitle#35]
Hi, 
Is a new release planned for the version 1.1.0 of material ?
Thanks

**Comment by hendraanggrian** [comment]
Yes, thanks for bringing it to my attention. I've skipped many beta and alpha versions just for this one.

**Comment by hendraanggrian** [comment]
Version 1.1.0 has been uploaded.
