### ISSUE TITLE
Migrate to mavenCentral

### ISSUE THREAD

**Issue by leviancode** [hendraanggrian/collapsingtoolbarlayout-subtitle#39]
Hello! Are there any plans to migrate from deprecated jcenter() to mavenCentral() ? Thanks!

**Comment by hendraanggrian** [comment]
Hi there, yes eventually this library will move to maven central. I will need to migrate my other libraries first, check back in a week or so.

**Comment by hendraanggrian** [comment]
The library has been migrated to maven central, but at the moment only on [Sonatype's snapshots repository](https://s01.oss.sonatype.org/content/repositories/snapshots).

Use version `1.3.0-SNAPSHOT`.
