### ISSUE TITLE
expandedTitleGravity="center_horizontal" not working.

### ISSUE THREAD

**Issue by michael-snow** [HendraAnggrian/collapsingtoolbarlayout-subtitle#4]
xml:

`   <android.support.design.widget.AppBarLayout
        android:id="@+id/app_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true"
        android:theme="@style/AppTheme.AppBarOverlay">

        <android.support.design.widget.SubtitleCollapsingToolbarLayout
            android:id="@+id/toolbar_layout"
            android:layout_width="match_parent"
            android:minHeight="@dimen/contact_profile_toolbar_min_height"
            app:contentScrim="?colorPrimary"
            app:expandedTitleMarginTop="@dimen/contact_profile_toolbar_lyt_ext_title_margin_top"
            app:layout_scrollFlags="scroll|exitUntilCollapsed"
            app:expandedTitleMargin="@dimen/contact_profile_toolbar_lyt_ext_title_margin"
            android:layout_height="@dimen/contact_profile_toolbar_lyt_height"
            app:subtitle="CollapsingToolbarLayout"
            app:title="Subtitle"
            android:fitsSystemWindows="true"
            app:expandedTitleGravity="center_horizontal">

            <View
                android:id="@+id/background"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:layout_collapseMode="parallax"
                android:scaleType="centerCrop"
                android:background="@color/colorPrimary" />

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                app:layout_collapseMode="pin"
                app:popupTheme="@style/AppTheme.PopupOverlay">

                <Space
                    android:id="@+id/circle_collapsed_target"
                    android:layout_width="@dimen/contact_profile_circle_collapsed"
                    android:layout_height="@dimen/contact_profile_circle_collapsed"/>

            </android.support.v7.widget.Toolbar>

        
        </android.support.design.widget.SubtitleCollapsingToolbarLayout>

    </android.support.design.widget.AppBarLayout> `

**Comment by HendraAnggrian** [comment]
@michael-snow thank you for the report. I'm currently doing some major code cleanup now and will fix this issue afterwards. Might take several days, but will let you know again when it's fixed, so hang in there.

**Comment by HendraAnggrian** [comment]
Version 0.4.1 is out, it now supports `center_horizontal` gravity, but unfortunately not much else.
I will need couple of days to test the remaining gravity.

**Comment by michael-snow** [comment]
Hi. thank you. its works. but expandedTitleGravity="center_horizontal" does not apply to subtitle. And app:expandedTitleMarginTop not works correctly
subtitle gravity screenshot 
[http://2.1m.yt/phH0J0I.png](url)

**Comment by HendraAnggrian** [comment]
Hello, you're right about that. Currently, the x point of subtitle mirrors the x point of the title. I'm planning to fix it in next release, but again, that could take several days.

Anyway, can you please explain about `app:expandedTitleMarginTop` being unable to work properly? The image url seem to be invalid.

**Comment by HendraAnggrian** [comment]
@michael-snow Version 0.4.5 is out to specifically address this issue. Title and subtitle now has separate x points for text centering with `center_horizontal` gravity. It should also support other gravities but too be honest I'm too lazy to test them all.

**Comment by michael-snow** [comment]
great thanks. its works Version 0.4.6
