### ISSUE TITLE
Change SubTitle text Color progrmmatically

### ISSUE THREAD

**Issue by hitesh-dhamshaniya** [HendraAnggrian/collapsingtoolbarlayout-subtitle#6]
We can change the setExpandedTitleColor & setCollapsedTitleColor but this is not affecting to subTile. 

I've applied text color in style and applied that style like this : 

` app:expandedSubtitleTextAppearance="@style/TextAppearance.AppCompat.Body1.Color"`

This worked fine, but I want to change its color dynamically  like we do for tile as : 

`setExpandedTitleColor(textSwatch.getTitleTextColor());`

Is there any way that I can do this programmatically?

**Comment by HendraAnggrian** [comment]
@hitesh-dhamshaniya My bad, this feels like something that should be there in the first place. Version 0.4.3 is out to support this, please try it :)

**Comment by hitesh-dhamshaniya** [comment]
Thanks @HendraAnggrian for a quick solution. It's working fine now.

**Comment by HendraAnggrian** [comment]
Cool :) let me know if you have another concern.
