### ISSUE TITLE
Title not sits bottom when not set SubTitle.

### ISSUE THREAD

**Issue by hitesh-dhamshaniya** [HendraAnggrian/collapsingtoolbarlayout-subtitle#8]
Hello there,

I am setting up sub title only when there will be long string for title, but I when there is no sub title title remain in Vertically center instead of sit in bottom.

**Comment by HendraAnggrian** [comment]
@hitesh-dhamshaniya hello, here's a SubtitleCollapsingToolbarLayout with a long title, no subtitle, and default gravity:

![screenshot_1495459385](https://cloud.githubusercontent.com/assets/11507430/26310885/a213d7fa-3f2c-11e7-99cf-6dc822fe2c51.png)

Clearly, I am unable to recreate the irregularities you have mentioned. Would you mind share a bit of code and screenshot? Also, what version are you using?

**Comment by hitesh-dhamshaniya** [comment]
Thank you very much @HendraAnggrian for your prompt replay.
I don't know what was a problem but It's resolve now.

**Comment by HendraAnggrian** [comment]
Sounds great! Feel free to reopen this issue if by any chance it happens again.
