### ISSUE TITLE
Set subtitle typeface methods not found

### ISSUE THREAD

**Issue by linotex** [HendraAnggrian/collapsingtoolbarlayout-subtitle#9]
Can I set subtitle typeface?

Thank you!

**Comment by HendraAnggrian** [comment]
@linotex you're right I seem to miss that part. I'll work on it and will update this thread again. In the meantime, you can set subtitle text appearance.

**Comment by linotex** [comment]
Thank you! I will waiting

**Comment by HendraAnggrian** [comment]
Hi @linotex, thanks for waiting. You can now customize collapsed/expanded subtitle typeface with version 0.7.0. Please try it and let me know how it goes.

**Comment by linotex** [comment]
Hi @HendraAnggrian! I have tried and it's work properly. Thank you very much.

**Comment by HendraAnggrian** [comment]
Cheers! Let me know if you find another one.
